### ISSUE TITLE
Upgrade to Ghost 4

### ISSUE THREAD

**Issue by karthikb351** [InternetFreedomFoundation/ghost-iffy#11]
[Ghost 4 is out](https://ghost.org/changelog/4/) and brings a bunch of performance improvements and features. Our theme is already compatible with Ghost 4, we just need to backup the current content and upgrade via the CLI.

**Comment by anoop-b** [comment]
Already Upgraded to v4 on release day. fe1352a299ada4bc87187f471fb159a294ce6511 should fix any issues with respect to theme. Should be safe to close this issue now.

**Comment by karthikb351** [comment]
Oh whoops. Thanks @anoop-b  :)
