### ISSUE TITLE
Broken Privacy link

### ISSUE THREAD

**Issue by kracekumar** [InternetFreedomFoundation/ghost-iffy#3]
Privacy link provided in [donation page](https://internetfreedom.in/donation-terms/) is [broken](https://internetfreedom.in/privacy).

![privacy_iff_404](https://cloud.githubusercontent.com/assets/311929/24238961/0e584822-0fd2-11e7-81b4-f3cb377fd8b9.png)

**Comment by karthikb351** [comment]
This has been fixed. Thanks @kracekumar!
